// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkFGvJKnsTRwPPDL9gEL3MtZSd-_5nqjY',
    appId: '1:835234085525:web:851f36f4efa69287d6399c',
    messagingSenderId: '835234085525',
    projectId: 'agro-kai',
    authDomain: 'agro-kai.firebaseapp.com',
    databaseURL: 'https://agro-kai-default-rtdb.firebaseio.com',
    storageBucket: 'agro-kai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFy4Rarj3WFT8VAHjwHehN3OZM9lVb3GY',
    appId: '1:835234085525:android:cbc39e2db22f598fd6399c',
    messagingSenderId: '835234085525',
    projectId: 'agro-kai',
    databaseURL: 'https://agro-kai-default-rtdb.firebaseio.com',
    storageBucket: 'agro-kai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGHXrxMxyuWqIfT7sNV4zLIyDnbxXuBwk',
    appId: '1:835234085525:ios:cdc054b9e80e022fd6399c',
    messagingSenderId: '835234085525',
    projectId: 'agro-kai',
    databaseURL: 'https://agro-kai-default-rtdb.firebaseio.com',
    storageBucket: 'agro-kai.appspot.com',
    iosBundleId: 'com.example.dummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGHXrxMxyuWqIfT7sNV4zLIyDnbxXuBwk',
    appId: '1:835234085525:ios:cdc054b9e80e022fd6399c',
    messagingSenderId: '835234085525',
    projectId: 'agro-kai',
    databaseURL: 'https://agro-kai-default-rtdb.firebaseio.com',
    storageBucket: 'agro-kai.appspot.com',
    iosBundleId: 'com.example.dummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkFGvJKnsTRwPPDL9gEL3MtZSd-_5nqjY',
    appId: '1:835234085525:web:372d8945fe9560bad6399c',
    messagingSenderId: '835234085525',
    projectId: 'agro-kai',
    authDomain: 'agro-kai.firebaseapp.com',
    databaseURL: 'https://agro-kai-default-rtdb.firebaseio.com',
    storageBucket: 'agro-kai.appspot.com',
  );
}
